#! /bin/sh

### BEGIN INIT INFO
# Provides:          sendinel-scheduler
# Required-Start:    $remote_fs $syslog sdcard-mount sendinel
# Required-Stop:     $remote_fs $syslog sdcard-mount sendinel
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sendinel scheduler
### END INIT INFO

sendinelPath="/media/sdcard/sendinel/Sendinel/sendinel"
pidFile="/tmp/sendinelScheduler.pid"

#################################
# TODO update this for release - see sendinel/scheduler.sh
#################################

case "$1" in
 start)
       echo -n "Starting Sendinel scheduler"
       cd $sendinelPath
       python "$sendinelPath/backend/scheduler.py" >> /tmp/sendinelScheduler.log 2>&1 &
       newPid=$!
       echo -n $newPid > $pidFile
       echo "."
       ;;
 stop)
       echo -n "Stopping sendinel scheduler "
       if [ -f "$pidFile" ]; then
           pid=$(cat $pidFile)
           kill $pid
           rm $pidFile
       else
           echo "Warning: Scheduler not running - no PID file found."
       fi

       echo "."
       ;;
 *)
       N=/etc/init.d/$NAME
       echo "Usage: $N {start|stop}" >&2
       exit 1
       ;;
esac

exit 0

