#! /bin/sh

### BEGIN INIT INFO
# Provides:          sendinel-scheduler
# Required-Start:    $remote_fs $syslog sendinel
# Required-Stop:     $remote_fs $syslog sendinel
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sendinel scheduler
### END INIT INFO

sendinelPath="%targetDir%/sendinel"
pidFile="/tmp/sendinelScheduler.pid"

start() {
    echo -n "Starting Sendinel scheduler"
    cd $sendinelPath && \
    su '%user%' -c "python '$sendinelPath/backend/scheduler.py' $pidFile"
    echo "."
}

stop() {
    echo -n "Stopping sendinel scheduler"
    if [ -f "$pidFile" ]; then
        pid=$(cat $pidFile)
        kill $pid
        # pid file should be removed by python
    else
        echo "Warning: Scheduler not running - no PID file found."
    fi

    echo "."
}

case "$1" in
 start)
    start
    ;;
 stop)
    stop
    ;;
 restart)
    stop
    start
    ;;
 *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
